### ISSUE TITLE
Log Detective vs. LogDetective

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/logdetective-website#158]
I have seen various variations of our name. I think it is time to say loudly what is the correct way. But I do not know what it is :)

Please cast your vote:

1. Log Detective
2. LogDetective
3. Logdetective

And in CLI, URLs...

a. log-detective (or log_detective)
b. logdetective
c. LogDetective
d. Log-Detective (or Log_Detective).

I have to say I am not fan of 'c' and 'd' as for cli I want to keep it lowercase only.
Did I forget some variation?

Based on your voting, I will create Guideline.md document with guidelines how to use the name.

**Comment by xsuchy** [comment]
And I will say my preference:

2. Log Detective 

b. logdetective

**Comment by FrostyX** [comment]
AFAIK the agreed-upon project name was "Log Detective". 

I don't remember what was the agreed-upon name for CLI (and our main hostname) but I think it makes sense to use `logdetective` since the GitHub repository, PyPI project, and CLI tool already use that name.

**Comment by TomasTomecek** [comment]
I always use "Log Detective" in writing and lately started using "logdetective" in code etc.

**Comment by praiskup** [comment]
Can you update the ticket with the final result?
