### ISSUE TITLE
Prepare starting/stopping script for VM for training

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/logdetective-website#182]

**Comment by xsuchy** [comment]
[g5.48xlarge](https://instances.vantage.sh/aws/ec2/g5.48xlarge) please in Europe (ireland)

**Comment by praiskup** [comment]
We could call: https://pagure.io/fedora-infra/ansible/blob/main/f/playbooks/hosts/logdetective01.fedorainfracloud.org.yml
